apiVersion: "v1"
kind: "LimitRange"
metadata:
  name: "limits" 
spec:
  limits:
    -
      type: "Pod"             # Setting pod limits
      max:
        cpu: "2" 
        memory: "256mi" 
      min:
        cpu: "200m" 
        memory: "6Mi" 
    -
      type: "Container"       # Setting container limits
      max:
        cpu: "2" 
        memory: "256mi" 
      min:
        cpu: "100m" 
        memory: "4Mi" 
      default:
        cpu: "300m" 
        memory: "200Mi" 
      defaultRequest:
        cpu: "200m" 
        memory: "100Mi" 
      maxLimitRequestRatio:
        cpu: "10"
